language: python

python:
    - 3.5
    - 3.6

install:
    - pip install -r requirements-test.txt
    - pip install -r requirements.txt

jobs:
  include:
    - script: bandit -r adoc
    - script: pytest .
