language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt

stages:
  - analysis
  - test

script: pytest

jobs:
  include:
    - stage: analysis
      script: bandit -r adoc
