language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install -r requirements-pdf.txt
  - pip install -r requirements-test.txt

stages:
  - analysis
  - test

script: pytest

jobs:
  include:
    - stage: analysis
      script: bandit -r adoc
