<!doctype html>
<head>
  <%namespace name="macros" file="macros.mako" />

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

  <title>${project.name} documentation</title>
  <meta name="description" content="" />

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300"
    rel="stylesheet" type="text/css">

  <style type="text/css">
<%include file="css-pygments.mako" />
<%include file="css-normalize.mako" />
<%include file="css-adoc.mako" />
<%include file="css-print.mako" />
  </style>
</head>
<body>

  <a href="#" id="top">Top</a>

  <div id="container">
    <div id="sidebar">
      <h1>Index</h1>

      <ul id="index">
        <li class="set">
          <h3>
              <a href="#content">README</a>
          </h3>
        </li>

        <li class="set">
          <h3>
            <a href="#api-reference">API Reference</a>
          </h3>
        </li>

        <li class="sep">
          <hr>
        </li>

        <li class="set">
          <h3 id="modules">
            <a href="#modules">Modules</a>
          </h3>

          ${macros.list_modules(project.modules)}
        </li>

        <li class="set">
          <h3 id="functions">
            <a href="#functions">Functions</a>
          </h3>

          <ul>
            ${macros.list_functions(project)}
          </ul>
        </li>

        <li class="set">
          <h3 id="classes">
            <a href="#classes">Classes</a>
          </h3>

          <ul>
            ${macros.list_classes(project)}
          </ul>
        </li>
      </ul>
    </div>

    <article id="content">
      ${macros.show_doc(project)}

      <section>
        <h1 class="section-title" id="api-reference">
          API Reference
        </h1>

        ${macros.show_modules(project.modules)}
      </section>
    </article>

    <div class="clear"> </div>

    <footer id="footer">
      <p>
        Generated by <a href="https://github.com/saalaa/adoc">adoc</a>
      </p>

      <p>
        Designed by <a href="http://nadh.in">Kailash Nadh</a>
      </p>
    </footer>
  </div>
</body>
</html>
